FROM openjdk:17-jre-slim

WORKDIR /app

COPY ../Nova-config-server/target/configserver-0.0.1-SNAPSHOT.jar /app/configserver-0.0.1-SNAPSHOT.jar

EXPOSE 8081

CMD ["java","-jar","/configserver-0.0.1-SNAPSHOT.jar"]